### PR TITLE
Fix MIDI issues from the fuzz-patch-1/oob_read_fixes merge.

### PR DESCRIPTION
**Pull request by AliceLR**
The merge between oob_read_fixes and fuzz-patch-1 broke some important hang fixes in fuzz-patch-1 that relied on an EOF state flag being set in the `mmread*` functions. IMO there weren't any particularly good options for reconciling these, but the least bad one was to get rid of the unnecessary extra IO abstraction and move the EOF state flag to the `mid_read_*` functions. If you'd prefer something less messy I can revise this patch.

Multiple files here should demonstrate the hang issue, but `leak-b87ea8e905057fb4ce372fdc8f840913230b73e8` is the first one that came up in my testing: [PROBLEM_MIDI.tar.gz](https://github.com/Konstanty/libmodplug/files/7962950/PROBLEM_MIDI.tar.gz). Note even with this the MIDI loader's slow loading issue isn't fixed, it's just a little less worse than before, and should no longer permanently hang.

Also fixes a -Wsign-compare warning at (former) line 1294.

edit: I haven't tested this with valid input files yet and won't have a chance to right away, sorry.

### CODE REVIEW

**Comment by sezero** [comment]
This one needs a rebase after PR/70 merge:
`BYTE buf[4] = {};` --> `BYTE buf[4] = {0,0,0,0};`
and `BYTE buf[2] = {};` --> `BYTE buf[2] = {0,0};`

**Comment by AliceLR** [comment]
OK, done. This patch still makes the initializers unnecessary so the patch is effectively the same.

**Comment by Konstanty** [comment]
Thanks

**Comment by AliceLR** [comment]
*Probably* the source of the rest of the slow loads caused by `load_mid.cpp`: the MIDI tracks are stored as an unordered linked list, so `Mid_ReadPatterns` will scan the entire track for events between the time values it wants for every track for every row.

A workaround might be scrapping the linked lists, loading the events into a heap, and then finishing with a fast heap sort.

**Pull request merged**
