### PR TITLE
ReadSTM: fix STM signature checks to be case-sensitive.

### PR DESCRIPTION
**Pull request by sezero**

### CODE REVIEW

**Comment by sagamusix** [comment]
Technically it doesn't matter what's put in those fields, ST2 and ST3 don't care about them. Another value that has been found in the wild for this field is "SWavePro", and "WUZAMOD!" supposedly exists, too (probably from a MOD->STM converter).
This should probably just check for valid ASCII characters (32-127) and validate all other header fields very toughly, like OpenMPT does.

**Comment by sezero** [comment]
Technically maybe, who knows,  but are there any file in the wild
with case-insensitive versions of those sigs, e.g. "!SCREAM!" and
not "!Scream!"?  Both libxmp and and libmikmod checks those sigs
case-sensitively; only libmodplug does it case-insensitively..

> "SWavePro", and "WUZAMOD!" 

Yeah, but I only touched what libmodplug checks at present.

**Comment by sagamusix** [comment]
I don't know if such files exist, but I thought that while you already fix this, you might just as well fix it with all cases in mind.

**Comment by sezero** [comment]
I don't know of any either.  So, I'd rather stick to existing sigs and
check them case-sensitively to avoid any false positives.

**Comment by sezero** [comment]
PING ?

**Comment by sezero** [comment]
PING ?

**Comment by sezero** [comment]
PING ?

**Pull request merged**
